<a href="https://colab.research.google.com/github/khj1116/python-coding/blob/main/0705(2%EC%B0%A8%EC%9B%90%EB%B0%B0%EC%97%B4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
def printhello(): #함수 정의
  print('hello world!')

#for i in range(5):
#  printhello()
i = 0
while i < 5:
  printhello()

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
hello world!
he

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-5737f7b029a3>", line 8, in <cell line: 7>
    printhello()
  File "<ipython-input-6-5737f7b029a3>", line 2, in printhello
    print('hello world!')
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/iostream.py", line 402, in write
    self.pub_thread.schedule(lambda : self._buffer.write(string))
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/iostream.py", line 203, in schedule
    self._event_pipe.send(b'')
  File "/usr/local/lib/python3.10/dist-packages/zmq/sugar/socket.py", line 620, in send
    return super().send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 746, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 793, in zmq.backend.cython.socket.Socket.send
  File "zmq/b

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-5737f7b029a3>", line 8, in <cell line: 7>
    printhello()
  File "<ipython-input-6-5737f7b029a3>", line 2, in printhello
    print('hello world!')
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/iostream.py", line 402, in write
    self.pub_thread.schedule(lambda : self._buffer.write(string))
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/iostream.py", line 203, in schedule
    self._event_pipe.send(b'')
  File "/usr/local/lib/python3.10/dist-packages/zmq/sugar/socket.py", line 620, in send
    return super().send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 746, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 793, in zmq.backend.cython.socket.Socket.send
  File "zmq/b

TypeError: object of type 'NoneType' has no len()

In [8]:
def printhello():
  print('hello world!')
  printhello()

  for i in range(5):
    printhello()
  # i = 0
  # while i < 5:
  # printhello()
  # i = i + 1


In [15]:
def get_sum(a,b): #함수 정의(매개변수 있음, 리턴값 있음)
  s = a + b  #s = 지역변수(get_sum에서만 사용가능)
  return s
result = get_sum(5,7)
print(result)
print(get_sum(4,5))


12
9


In [18]:
def sum_many(*C401): #복수 개의 가변적인 입력값이 들어올 때 * 사용
  sum = 0
  for i in C401:
    sum += i
  return sum
print(sum_many(1,2,5,41,10))

59


In [22]:
def add_and_sum(a,b): #리턴값이 복수개

  return a+b, a*b #튜플로 구성
result = add_and_sum(25,37) #결과를 튜플로 받는다
print(result)
r1, r2 = add_and_sum(10,15) #결과를 별개의 변수로 나누어 저장
print(r1, r2)

(62, 925)
25 150


In [26]:
a = '첫번째 방' #참조, 초기화
def v(a): #정의하는 코드
  a = a * 2 #함수 내에서는 전역변수값을 수정 할 수 없다.
  print(a)  #지역변수
v(a)  #실행하는 코드
print(a) #전역변수

첫번째 방첫번째 방
첫번째 방


In [33]:
a = '첫번째'
def v():
  global a #전역변수 접근하려면 global 사용
  a = a * 2
v()
print(a)


첫번째첫번째


In [37]:
x = 1
y = 3
def change():
  global x ,y #전역변수 x, y
  x = 2
  y = 5
  y = y + 4
change()
print(x,y) #전역 x, 전역 y

2 9


In [39]:
def star(n):
  for i in range(n):
    print('*' * (i+1))

star(10)

*
**
***
****
*****
******
*******
********
*********
**********


In [48]:
#--------------------------------------------(정의)
def add(num1,num2):
  print(num1, '+', num2, '=', num1+num2)
def sub(num1,num2):
  print(num1, '-', num2, '=', num1-num2)
def mul(num1, num2):
  print(num1, '*', num2, '=', num1*num2)
def div(num1,num2):
  print(num1, '/', num2, '=', num1/num2)

#--------------------------------------------(실행)
num1 = int(input('첫번째 수 : '))
num2 = int(input('두번째 수 : '))
op = input('어떤계산을 원하시나요?(+,-,*,/) : ')
if op == '+':
  add(num1,num2)
elif op =='-':
  sub(num1,num2)
elif op=='*':
  mul(num1,num2)
elif op == '/':
  div(num1,num2)


첫번째 수 : 1
두번째 수 : 2
어떤계산을 원하시나요?(+,-,*,/) : /
1 / 2 = 0.5


In [60]:


def tri(a,b):
  a = (a * b)/2
  return a
def squ(x,y):
  x = x * y
  return x
def cir(r):
  r = 3.14 * r**2
  return r

def none(a):
  a = a + 1
  print('그냥',a)
while True:
  sel = input("도형을 선택하세요(삼각형/사각형/원) : ")
  if sel == '삼각형':
      밑변 = int(input("밑변 : "))
      높이 = int(input("높이 : "))
      width = tri(밑변, 높이)
      print("넓이는 : {}입니다".format(width(밑변, 높이)))
  elif sel == '사각형':
      가로 = int(input("가로 : "))
      세로 = int(input("세로 : "))
      square = squ(가로,세로)
      print("넓이는 : %d입니다." % squ(가로, 세로))
  elif sel == '원':
      반지름 = int(input("반지름 : "))
      rad = cir(반지름)
      print(f"원의 넓이는 : {rad}입니다.")
  else:
      print("잘못입력했습니다.")
  if  a == 'q':
    break


도형을 선택하세요(삼각형/사각형/원) : q
잘못입력했습니다.


KeyboardInterrupt: Interrupted by user

In [63]:
#클래스
class cookie: #class 정의
  pass

a = cookie()     #클래스 선언 a는 객체
b = cookie()      # b 객체(cookie로 만든 개체), cookie의 인스턴스
print(a)
print(b)

In [69]:
class calcul:
  def setup(self, a,b):   #클래스내에 있는 함수는 메서드
    self.n1 = a
    self.n2 = b
  def add(self):
    result = self.n1 + self.n2
    return result

In [72]:
a = calcul()   #객체 생성 a
a.setup(2,8)    #멤버변수 정의

b = calcul()   #객체 생성 b
b.setup(32,80) #멤버변수 정의

print(a.n1)
print(b.n1)

print(a.add()) #덧셈 메서드(함수) 실행
print(b.add()) #덧셈 메서드(함수) 실행


2
32
10
112


In [83]:
class calcul:
  def __init__(self,a,b):   #생성자(특수메서드)
    self.num1 = a
    self.num2 = b

  def add(self):
    result = self.n1 + self.n2
    return result

a = calcul(4,9)
print(a.n1)
print(b.n2)
print(a.add())
print(b.add())

AttributeError: 'calcul' object has no attribute 'n1'

In [96]:
class parent:
  def __init__(self, a, b, c): #이름, 나이, 성별 변수 정의
    self.name = a
    self.age = b
    self.gender = c
  def myinfo():
      print(f"{self.name} {self.age} {self.gender}")

    #객체를 생성
    #내용출력 메서드 만드시오
    #현준 30 남

me = parent('현준', 30, '남')
sister = parent('시은', 28, '여')

print(me.myinfo())





TypeError: parent.myinfo() takes 0 positional arguments but 1 was given

In [16]:
import numpy as np
arr1 = np.array([1,2,3,4,5]) #1행
print(arr1)
arr2 = np.array([[1,2,3], #1행(가로)  #3열(세로)
                 [4,5,6]]) #2행(가로)
print(arr2)
arr3 = np.array([[[1,2,10],[3,4,10]],[[5,6,10],[7,8,10]]])  #2(높이)x2(행)x2(열)
print()
print(arr3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]

[[[ 1  2 10]
  [ 3  4 10]]

 [[ 5  6 10]
  [ 7  8 10]]]


In [19]:
print(arr1.shape) #1차원 속성(튜플형식으로 반환)
print(arr2.shape) #2차원 속성
print(arr3.shape) #3차원 속성 2x2x3

(5,)
(2, 3)
(2, 2, 3)


In [23]:
print(arr1.ndim) #차원의 수
print(arr2.ndim)
print(arr3.ndim)

print(arr1.size)  #요소의 개수
print(arr2.size)
print(arr3.size)

print(arr1.dtype)   #요소 1개당 크기(8바이트)
print(arr2.dtype)
print(arr3.dtype)

1
2
3
5
6
12
int64
int64
int64


In [26]:


a = np.array([[[1,2,10],[3,4,10]],[[5,6,10],[7,8,10]]])

print(f"Shape: {a.shape}")
print(f"number of dimension: {a.ndim}")
print(f"data shape: {a.dtype.name}")
print(f"itemsize: {a.itemsize} bytes")
print(f"size: {a.size} bytes")

Shape: (2, 2, 3)
number of dimension: 3
data shape: int64
itemsize: 8 bytes
size: 12 bytes


In [101]:
# 16시부터 상담 : 순서정하기 랜덤수를 넣어 번호를 나열
import random
lt = 0
list = []
check = [False for i in range(12)]
for i in range(11):
    while True:
      num = random.randint(1,11)
      if check[num] == False:
        check[num] = True
        break
    list.append(num)
print(list)





[7, 5, 2, 1, 9, 8, 11, 3, 4, 6, 10]


In [31]:
a1 = np.array([0,1,2,3,4,5,6,7,8,9])
a1
type(a1)

answer = []
for i in a1:
  answer.append(2*i)
print(answer)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [36]:
a = np.array([1,2,3]) #1차원 배열
b = np.array([10,20,30])
print(2*a+b)
print(a==2)
print(b>10)
print((a==2)&(b>10)) # &(그리고), |(또는)

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [40]:
i = np.array([[0,1,2],[3,4,5]])
print(i)
len(i)
len(i[0])

[[0 1 2]
 [3 4 5]]


3

In [44]:
b = np.array([[10,20,30,40],[50,60,70,80]])
print(b)

[[10 20 30 40]
 [50 60 70 80]]


In [46]:
c = np.array([[[1,2,3,4],[5,6,7,8], [9,10,11,12]],[[11,12,13,14],[15,16,17,18],[19,20,21,22]]])
print(c)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


In [50]:
print(len(c))
print(len(c[0]))
print(len(c[0][0]))


2
3
4


In [52]:
a = np.array([0,1,2,3,4])
print(a[2])
print(a[-1])

2
4


In [55]:
a = np.array([[0,1,2],[3,4,5]])
print(a)
print(a[0,0])
print(a[-1][-1])

[[0 1 2]
 [3 4 5]]
0
5


In [59]:
ar1 = np.array([1,2,3])
ar2 = np.array([4,5,6])

print(ar1+ar2)
print(ar1-ar2)
print(ar1*ar2)
print(ar1/ar2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [62]:
ar1 = np.array([[1,2,3] ,[4,5,6]])   #2차원 배열
ar2 = np.array([1,2,3]) #1차원 배열
print(ar1+ar2)  #브로드 캐스팅

[[2 4 6]
 [5 7 9]]
